name: Build(oneformer)

env:
#   BASE_IMAGE: "nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04"

#   PYTHON_VERSION: "3.10.15"

#   PYTORCH_VERSION: "1.13.1"
#   PYTORCH_VERSION_SUFFIX: "+cu117"
#   TORCHVISION_VERSION: "0.14.1"
#   TORCHVISION_VERSION_SUFFIX: "+cu117"
#   TORCHAUDIO_VERSION: "0.13.1"
#   TORCHAUDIO_VERSION_SUFFIX: "+cu117"
#   PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/cu117/torch_stable.html"

  IMAGE_TAG: "1.13.1-py3.10.15-cuda11.7.1-devel-ubuntu20.04"

on:
  push:
    branches:
      - master
    paths:
      - 'docker/oneformer/**'
      - '.github/workflows/docker_build_oneformer_ubuntu20.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build . -f docker/oneformer/Dockerfile -t torch-docker/oneformer:${IMAGE_TAG} && docker tag torch-docker/oneformer:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/oneformer:${IMAGE_TAG}

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/oneformer:${IMAGE_TAG}
